//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Deployment.Common.ErrorResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnglishErrorCodes
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishErrorCodes()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Deployment.Common.ErrorResources.EnglishErrorCodes", typeof(EnglishErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error signing you in.
        /// </summary>
        public static string AzureLoginFailed
        {
            get
            {
                return ResourceManager.GetString("AzureLoginFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry,the azure token expired, please try again in a new tab.
        /// </summary>
        public static string AzureTokenExpired
        {
            get
            {
                return ResourceManager.GetString("AzureTokenExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Azure website name is already taken.
        /// </summary>
        public static string AzureWebsiteNameTaken
        {
            get
            {
                return ResourceManager.GetString("AzureWebsiteNameTaken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot start PowerShell.
        /// </summary>
        public static string CannotStartPowerShell
        {
            get
            {
                return ResourceManager.GetString("CannotStartPowerShell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password is missing.
        /// </summary>
        public static string CreateTaskPasswordMissing
        {
            get
            {
                return ResourceManager.GetString("CreateTaskPasswordMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credential Guard is enabled on this computer and does not yet support Windows Task Scheduler. Please choose a different computer..
        /// </summary>
        public static string CredentialGuardEnabled
        {
            get
            {
                return ResourceManager.GetString("CredentialGuardEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot read from the Credential Manager or the entry was not found.
        /// </summary>
        public static string CredMgrReadError
        {
            get
            {
                return ResourceManager.GetString("CredMgrReadError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the Credential Manager.
        /// </summary>
        public static string CredMgrWriteError
        {
            get
            {
                return ResourceManager.GetString("CredMgrWriteError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error has occured, see additional details to learn more.
        /// </summary>
        public static string DefaultErrorCode
        {
            get
            {
                return ResourceManager.GetString("DefaultErrorCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login failed, please check that you have entered in the correct credentials.
        /// </summary>
        public static string DefaultLoginFailed
        {
            get
            {
                return ResourceManager.GetString("DefaultLoginFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This template requires group policy &quot;Network access: Do not allow storage of passwords and credentials for network authentication&quot; to be disabled.
        /// </summary>
        public static string DisabledDomainCredsEnabled
        {
            get
            {
                return ResourceManager.GetString("DisabledDomainCredsEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login failed for user.
        /// </summary>
        public static string ImpersonationFailed
        {
            get
            {
                return ResourceManager.GetString("ImpersonationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login failed, check that you have entered in the correct Windows credentials.
        /// </summary>
        public static string IncorrectNTCredentials
        {
            get
            {
                return ResourceManager.GetString("IncorrectNTCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing SQL Tools failed, please verify you are executing the installer as an Administrator.
        /// </summary>
        public static string InstallSQLToolsFailed
        {
            get
            {
                return ResourceManager.GetString("InstallSQLToolsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PowerShell version too low - please upgrade to latest version https://msdn.microsoft.com/en-us/powershell/wmf/5.0/requirements&quot;.
        /// </summary>
        public static string LowPowerShellVersion
        {
            get
            {
                return ResourceManager.GetString("LowPowerShellVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not activate replication profile.
        /// </summary>
        public static string MsCrm_ErrorActivateProfile
        {
            get
            {
                return ResourceManager.GetString("MsCrm_ErrorActivateProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not create replication profile.
        /// </summary>
        public static string MsCrm_ErrorCreateProfile
        {
            get
            {
                return ResourceManager.GetString("MsCrm_ErrorCreateProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No CRM organization with this URL could be found.
        /// </summary>
        public static string MsCrm_NoOrg
        {
            get
            {
                return ResourceManager.GetString("MsCrm_NoOrg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Dynamics CRM organizations were found.
        /// </summary>
        public static string MsCrm_NoOrgs
        {
            get
            {
                return ResourceManager.GetString("MsCrm_NoOrgs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No SQL databases were found in the selected SQL Server.
        /// </summary>
        public static string NoDatabasesFound
        {
            get
            {
                return ResourceManager.GetString("NoDatabasesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This program needs to be executed as an adminstrator with elevated permissions.
        /// </summary>
        public static string NotAdmin
        {
            get
            {
                return ResourceManager.GetString("NotAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This does not look like an SCCM database or you do not have read permissions.
        /// </summary>
        public static string NotSccmDB
        {
            get
            {
                return ResourceManager.GetString("NotSccmDB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to run the scheduled task, please check Task Scheduler.
        /// </summary>
        public static string RunningTaskFailed
        {
            get
            {
                return ResourceManager.GetString("RunningTaskFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The SCCM scheduled task could not be found.
        /// </summary>
        public static string SccmTaskNotFound
        {
            get
            {
                return ResourceManager.GetString("SccmTaskNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SCCM version format has an unexpected format.
        /// </summary>
        public static string SccmVersionFormatUnexpected
        {
            get
            {
                return ResourceManager.GetString("SccmVersionFormatUnexpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find SCCM version.
        /// </summary>
        public static string SccmVersionNotFound
        {
            get
            {
                return ResourceManager.GetString("SccmVersionNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SCCM version is lower than expected (should be at least 2012 R2 SP1).
        /// </summary>
        public static string SccmVersionTooLow
        {
            get
            {
                return ResourceManager.GetString("SccmVersionTooLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The target SQL server edition cannot be Express or local DB.
        /// </summary>
        public static string SQL_DenyLocalAndExpress
        {
            get
            {
                return ResourceManager.GetString("SQL_DenyLocalAndExpress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure SQL Data Warehouse is not supported.
        /// </summary>
        public static string SQL_DenyPDW
        {
            get
            {
                return ResourceManager.GetString("SQL_DenyPDW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The target SQL server must be at least version 2012.
        /// </summary>
        public static string SQL_VersionTooLow
        {
            get
            {
                return ResourceManager.GetString("SQL_VersionTooLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Azure Sql database server is already taken.
        /// </summary>
        public static string SqlDatabaseAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("SqlDatabaseAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login to SQL failed.
        /// </summary>
        public static string SqlLoginFailed
        {
            get
            {
                return ResourceManager.GetString("SqlLoginFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The scheduled task did not complete successfully.
        /// </summary>
        public static string TaskSchedulerRunFailed
        {
            get
            {
                return ResourceManager.GetString("TaskSchedulerRunFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, one or more of the accounts you entered could not be found.
        /// </summary>
        public static string TwitterAccountsInvalid
        {
            get
            {
                return ResourceManager.GetString("TwitterAccountsInvalid", resourceCulture);
            }
        }
    }
}